apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_USER = gitea
    RUN_MODE = prod

    [security]
    INTERNAL_TOKEN = glXtv83JUc4NQ0RowkSlVnLlVD5lJGE4DC3uFckvJhCuJnNXEpIYLriYnCfXK8FaDELLYtRAsiiOFjlSIK2kLUl7QE8Et31O8WHD6Ld4f
    INSTALL_LOCK   = true
    SECRET_KEY     = g8nwStpuWF
    PASSWORD_COMPLEXITY = off

    [oauth2]
    ENABLE = false

    [database]
    DB_TYPE  = postgres
    HOST     = gitea-postgresql:5432
    NAME     = gitea
    USER     = gitea
    PASSWD   = gitea
    SSL_MODE = disable

    [repository]
    ROOT = /gitea-repositories

    [server]
    ROOT_URL         = http://@HOSTNAME
    SSH_DOMAIN       = @HOSTNAME
    DOMAIN           = @HOSTNAME
    HTTP_PORT        = 3000
    SSH_PORT         = 2022
    DISABLE_SSH      = false
    START_SSH_SERVER = true
    LFS_START_SERVER = false
    OFFLINE_MODE     = false

    [mailer]
    ENABLED = false

    [service]
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    DISABLE_REGISTRATION              = false
    ENABLE_CAPTCHA                    = false
    REQUIRE_SIGNIN_VIEW               = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.example.org

    [picture]
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = true

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false

    [session]
    PROVIDER = file

    [log]
    MODE      = file
    LEVEL     = Info
    ROOT_PATH = /home/gitea/log

    [markup.asciidoc]
    ENABLED = true
    FILE_EXTENSIONS = .adoc,.asciidoc
    RENDER_COMMAND = "asciidoc --out-file=- -"
    IS_INPUT_FILE = false
